- cloudnetpy/categorize/categorize.py
- cloudnetpy/instruments/ceilo.py
- cloudnetpy/instruments/jenoptik.py
- cloudnetpy/instruments/mira.py
- cloudnetpy/instruments/rpg.py
- cloudnetpy/output.py
- cloudnetpy/products/classification.py
- cloudnetpy/products/drizzle.py
- cloudnetpy/products/iwc.py
- cloudnetpy/products/lwc.py
- cloudnetpy/version.py
- tests/unit/test_output.py
- tests/unit/test_rpg.py
This PR adds:
- Option to keep UUID of an existing file (only the data is overwritten).
- Bucharest chm15k lidar calibration info.
> Overwrite option

- cloudnetpy/categorize/categorize.py
- cloudnetpy/categorize/model.py
- cloudnetpy/categorize/radar.py
- cloudnetpy/instruments/rpg.py
- tests/unit/test_radar.py
This PR:
- Removes redundant attribute from the radar class
- Improves documentation of the attributes and functions
> Radar object

- cloudnetpy/categorize/classify.py
- cloudnetpy/categorize/droplet.py
- cloudnetpy/categorize/falling.py
- cloudnetpy/categorize/freezing.py
- cloudnetpy/categorize/insects.py
- cloudnetpy/categorize/melting.py
This PR adds more references to the classification methods.
> Add references

- cloudnetpy/categorize/categorize.py
- cloudnetpy/instruments/ceilo.py
- cloudnetpy/instruments/jenoptik.py
- cloudnetpy/instruments/mira.py
- cloudnetpy/instruments/rpg.py
- cloudnetpy/output.py
- cloudnetpy/products/product_tools.py
- tests/meta/metadata_config.ini
- tests/unit/test_output.py
This PR 
- adds `source_file_uuids` to the global attributes
- adds more publications to `references` attributes
> Provenance

- cloudnetpy/categorize/categorize.py
- cloudnetpy/categorize/mwr.py
- cloudnetpy/instruments/ceilo.py
- cloudnetpy/instruments/mira.py
- cloudnetpy/instruments/rpg.py
- cloudnetpy/output.py
- cloudnetpy/products/classification.py
- cloudnetpy/products/drizzle.py
- cloudnetpy/products/iwc.py
- cloudnetpy/products/lwc.py
- cloudnetpy/version.py
- tests/run_example_processing_and_tests.py
This PR:
- adds optional uuid argument to processing API functions
- add another possible LWP variable name
> UUID argument

- cloudnetpy/plotting/legacy_meta.py
- cloudnetpy/plotting/plot_meta.py
- cloudnetpy/plotting/plotting.py
- tests/unit/test_meta_for_old_files.py
- tests/unit/test_plotting.py
Adds a feature for MWR data plotting
> Plot mwr file data

- cloudnetpy/instruments/rpg.py
- cloudnetpy/utils.py
- setup.py
- tests/unit/test_rpg.py
- tests/unit/test_utils.py
This PR adds:
- Optional `date` parameter to `rpg2nc` function for validating date of the input files.
- Bug fix (and better tests) for RPG timestamp to date conversion.
- Small fixes and tests for `rpg2nc`.
> Rpg date validation

- cloudnetpy/plotting/__init__.py
- cloudnetpy/plotting/plotting.py
- tests/unit/test_plotting.py
This PR add simple plotting routine for legacy files.
> Legacy plots

- cloudnetpy/categorize/atmos.py
- cloudnetpy/products/classification.py
- tests/data_quality/data_quality_config.ini
- tests/meta/metadata_config.ini
- tests/unit/test_atmos.py
- tests/unit/test_classification.py
This PR adds lowest cloud bases and highest cloud tops into classification file.
> Add cloud top and base variables

- cloudnetpy/plotting/plotting.py
- tests/unit/test_plotting.py
Improves MWR visualizations:
- Cuts plots when time gaps
- Improves data visibility
- Fit noise filter to length of a data set
> Mwr visualization improvements

- cloudnetpy/categorize/categorize.py
- cloudnetpy/categorize/radar.py
- cloudnetpy/instruments/hatpro.py
- cloudnetpy/instruments/lufft.py
- cloudnetpy/instruments/nc_radar.py
- cloudnetpy/instruments/rpg.py
- cloudnetpy/instruments/vaisala.py
- Adds filtering of obvious vertical and horizontal stripes from categorize product
- Starts using logging
> Stripe filter

- cloudnetpy/plotting/plotting.py
The dimensions include width, height and margins which can be used to align multiple figures.
> Return dimensions of generated figure

- cloudnetpy/instruments/rpg.py
- Adds screening of low spectral width values. Removes noise seen e.g. [here](https://cloudnet.fmi.fi/api/download/image/20220209_hyytiala_rpg-fmcw-94-5538c8b0-Zh.png).
> Add screening of low width values

- cloudnetpy/instruments/mira.py
- cloudnetpy/products/drizzle.py
- cloudnetpy/products/drizzle_error.py
- cloudnetpy/products/drizzle_tools.py
- cloudnetpy/utils.py
Enables generation of Cloudnet `drizzle` product with cloud radars that do not provide spectral width
> Drizzle fix

- bump-version
Script for increasing cloudnetPy version number.
> Add version bumb script

- cloudnetpy/instruments/disdrometer.py
closes #52
Signed-off-by: Andreas Foth
> added rain_fall_rate_1_min_total and rain_fall_rate_1_min_solid

- cloudnetpy/categorize/categorize.py
- cloudnetpy/categorize/classify.py
- cloudnetpy/categorize/containers.py
- cloudnetpy/categorize/insects.py
- cloudnetpy/plotting/plot_meta.py
- tests/unit/test_drizzle_error.py
> Restore insect probability

- cloudnetpy/instruments/rpg_reader.py
In a quick test runtime improved from 4.1 s to 1.8 s.
> Optimize HATPRO binary file reading speed

- cloudnetpy/instruments/mira.py
> Level1b conversion add mira files as list

- cloudnetpy/plotting/plotting.py
Fixed the subtitle for the second plot in "compare_files"
> Minor fix to compare_files function in plotting.py

- cloudnetpy/model_evaluation/plotting/plotting.py
- cloudnetpy/plotting/__init__.py
- cloudnetpy/plotting/plot_meta.py
- cloudnetpy/plotting/plotting.py
- tests/unit/test_plotting.py
An attempt to simplify plotting..
> Plotting refactor

- cloudnetpy/categorize/containers.py
- cloudnetpy/categorize/insects.py
> Phantom rain
